### ISSUE TITLE
Using the configuration file to define separate configurations

### ISSUE THREAD

**Issue by waahhhh** [ytdl-org/youtube-dl#22187]
## Checklist

- [x] I'm reporting a feature request
- [x] I've verified that I'm running youtube-dl version **2019.08.13**
- [x] I've searched the bugtracker for similar feature requests including closed ones

## Description

  
It would be pretty nice if we could use the configuration file to define separate configurations.  
As example [in (TOML-Syntax)](https://github.com/toml-lang/toml):  
```toml
[extractor-a]
x=true
audio-format="mp3"

[extractor-b]
o="S%(season_number)s_E%(episode_number)s_%(title)s.%(ext)s"
```

If we pass an URL that matches "extractor-a", we get an mp3 file.  
If we pass an URL that matches "extractor-b", we get a video file that uses a different output template.
